### ISSUE TITLE
LSTM use in PPO

### ISSUE THREAD

**Issue by npitsillos** [MarcoMeter/neroRL#9]
Hello,

Thank you for the nice implementation.  This is more of a question rather than a problem with code.  I am finding it quite hard to nail down what the process is when using LSTM cells in the policy. Assume you have a sequence length of 10 timesteps and you sample 128 sequences.  That means your observation is 10, 128, state_dim.  Now your actions and log_probs will also be of 10, 128, 1. Am I right on this?  Further do you then leave those dimensions as is and calculate the loss? Can you elaborate on the process a bit more on how to construct the loss when using these dimensions?

If you could elaborate a bit on the process I would greatly appreciate it!

**Comment by MarcoMeter** [comment]
Hi @npitsillos 
the data is fed to the recurrent layer like you said `(10, 128, state_dim)`. The result of the recurrent layer is respahed to `(10 * 128, state_dim)`. Basically the remaining layers of the model treat each item of the sequence individually. So does the loss, except that padded items are masked. The only component that does utilize 3 dimensions, is the recurrent layer. For the loss and everything else it is just 2 dimensions.

Is this helpful to you?

**Comment by MarcoMeter** [comment]
You can also check out my baseline implementation, which isolates the recurrent PPO setup as much as possible.
https://github.com/MarcoMeter/recurrent-ppo-truncated-bptt

**Comment by npitsillos** [comment]
Yes this is helpful! And also I was referencing that repo before in the issue the code was the same and I got confused as to which repo I should use. One final thing the idea behind the masks is to mask out those timesteps that have been padded with 0s?

Thank you again for your help!

**Comment by npitsillos** [comment]
As a final example the mask is supposed to be of the same dimensionality (10,128) to select those values for the loss

**Comment by MarcoMeter** [comment]
Yes, you are right. The mask masks out time steps that were added due to zero padding.
The masks' shape is `(10*128)`. As it is not part of the forward pass of the model it does not need to be in the shape of `(sequence length, num sequences`.

**Comment by npitsillos** [comment]
Thank you very much for the explanation! This has helped me a lot in implementing my own repo!

**Comment by MarcoMeter** [comment]
No problem, you are welcome!
